// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSu2BPgu4U3zJz4uCsauZ5XrP4VkoKhvg',
    appId: '1:142926153956:web:1c86a4e36d33158e1104f1',
    messagingSenderId: '142926153956',
    projectId: 'flutter-iti-ee6c6',
    authDomain: 'flutter-iti-ee6c6.firebaseapp.com',
    storageBucket: 'flutter-iti-ee6c6.firebasestorage.app',
    measurementId: 'G-K909HKN64B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyICQftUQ3F8vYInM3D-F_dKAFkHFriO8',
    appId: '1:142926153956:android:f4c4de4bcc81b6d21104f1',
    messagingSenderId: '142926153956',
    projectId: 'flutter-iti-ee6c6',
    storageBucket: 'flutter-iti-ee6c6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSu2BPgu4U3zJz4uCsauZ5XrP4VkoKhvg',
    appId: '1:142926153956:web:7096e7949eb3a1c11104f1',
    messagingSenderId: '142926153956',
    projectId: 'flutter-iti-ee6c6',
    authDomain: 'flutter-iti-ee6c6.firebaseapp.com',
    storageBucket: 'flutter-iti-ee6c6.firebasestorage.app',
    measurementId: 'G-546ZZTXM8L',
  );
}
